# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: posupdate.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fposupdate.proto\"\xad\x02\n\x0ePositionUpdate\x12\x0c\n\x04line\x18\x01 \x01(\t\x12\x0b\n\x03veh\x18\x02 \x01(\t\x12\x0b\n\x03lat\x18\x03 \x01(\x01\x12\x0b\n\x03lon\x18\x04 \x01(\x01\x12\x14\n\x07heading\x18\x05 \x01(\x05H\x00\x88\x01\x01\x12\x12\n\x05speed\x18\x06 \x01(\x05H\x01\x88\x01\x01\x12\x13\n\x06tripId\x18\x07 \x01(\tH\x02\x88\x01\x01\x12\x16\n\tdirection\x18\x08 \x01(\x05H\x03\x88\x01\x01\x12\x15\n\x08nextStop\x18\t \x01(\tH\x04\x88\x01\x01\x12\x11\n\x04\x66ull\x18\n \x01(\x05H\x05\x88\x01\x01\x12\x14\n\x07timerec\x18\x0b \x01(\x03H\x06\x88\x01\x01\x42\n\n\x08_headingB\x08\n\x06_speedB\t\n\x07_tripIdB\x0c\n\n_directionB\x0b\n\t_nextStopB\x07\n\x05_fullB\n\n\x08_timerecb\x06proto3')



_POSITIONUPDATE = DESCRIPTOR.message_types_by_name['PositionUpdate']
PositionUpdate = _reflection.GeneratedProtocolMessageType('PositionUpdate', (_message.Message,), {
  'DESCRIPTOR' : _POSITIONUPDATE,
  '__module__' : 'posupdate_pb2'
  # @@protoc_insertion_point(class_scope:PositionUpdate)
  })
_sym_db.RegisterMessage(PositionUpdate)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _POSITIONUPDATE._serialized_start=20
  _POSITIONUPDATE._serialized_end=321
# @@protoc_insertion_point(module_scope)
